In [11]:
import numpy as np

NumPy linalg
============

In [12]:
A = np.array([[3, 4], [2, 3]])

In [13]:
A.T

array([[3, 2],
       [4, 3]])

In [14]:
np.linalg.inv(A)

array([[ 3., -4.],
       [-2.,  3.]])

In [15]:
np.linalg.matrix_rank(A)

2

In [16]:
B = np.array([[1, 0], [0, 0]])

In [17]:
np.linalg.matrix_rank(B)

1

In [18]:
b = np.array([[1], [2]])

In [19]:
x = np.linalg.solve(A, b)
x

array([[-5.],
       [ 4.]])

In [20]:
np.dot(A, x)

array([[1.],
       [2.]])

## Exercise - solving a system of linear equations

In [40]:
A = np.array([[2,1,1],[-5,-3,0],[1,1,-1]])
# with additional row
# A = np.array([[2,1,1],[-5,-3,0],[1,1,-1],[0,5,-1]])

In [41]:
b = np.array([-1,1,-2])

In [42]:
np.linalg.matrix_rank(A)

3

In [43]:
A_inv = np.linalg.inv(A)

In [44]:
x = np.dot(A_inv,b)
x

array([  7., -12.,  -3.])

In [45]:
np.dot(A,x)

array([-1.,  1., -2.])

In [46]:
# alternative
np.linalg.solve(A,b)

array([  7., -12.,  -3.])