In [37]:
import numpy as np

In [38]:
dist_to_origin = [0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391]

In [42]:
dist = np.array(dist_to_origin)
dist = dist.reshape(1,10)
dist_T = dist.reshape(10,1)

In [46]:
distances = np.abs(dist - dist_T)
distances

array([[   0, 1498, 1063, 1968, 1498, 1758, 1469, 1472, 2230, 2391],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1063,  435,    0,  905,  435,  695,  406,  409, 1167, 1328],
       [1968,  470,  905,    0,  470,  210,  499,  496,  262,  423],
       [1498,    0,  435,  470,    0,  260,   29,   26,  732,  893],
       [1758,  260,  695,  210,  260,    0,  289,  286,  472,  633],
       [1469,   29,  406,  499,   29,  289,    0,    3,  761,  922],
       [1472,   26,  409,  496,   26,  286,    3,    0,  758,  919],
       [2230,  732, 1167,  262,  732,  472,  761,  758,    0,  161],
       [2391,  893, 1328,  423,  893,  633,  922,  919,  161,    0]])

In [47]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [48]:
b = a  # "a" and "b" are bound to the same array
b[0] = 5
a

array([5, 1, 2, 3, 4])