In [1]:
import numpy as np

## Step 1

In [31]:
a = np.arange(1,37)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

## Step 2

In [33]:
b = a.reshape(6,6)
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

## Step 3

In [34]:
c = b[:,1]
c

array([ 2,  8, 14, 20, 26, 32])

## Step 4

In [39]:
d = b[:2,4:]
d

array([[ 5,  6],
       [11, 12]])

## Step 5

In [43]:
e = b[5,4:]
e

array([35, 36])

## Step 6

In [44]:
f = b[2::2,::2]
f

array([[13, 15, 17],
       [25, 27, 29]])